/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fcgs.gui;

import com.fcgs.runner.FcgsGuiRunner;
import com.fcgs.service.domain.TagTypeEnum;
import com.fcgs.service.util.GCResults;
import com.fcgs.templates.SsrTemplateEnum;
import com.pids.core.exception.ExceptionUtils;
import com.pids.core.template.reader.SimpleTemplateReader;
import com.pids.core.template.reader.TemplateReader;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.FilenameUtils;
import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.File;

/**
 * @author jiangbin
 */
public class FcgsMainFrame extends javax.swing.JFrame {
    private Logger log = LoggerFactory.getLogger(FcgsMainFrame.class);

    /**
     * Creates new form FcgsMainFrame
     */
    public FcgsMainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);//窗口居中
        this.openDialog = new FileDialog(this, "Open Gene CSV File", FileDialog.LOAD);
        this.saveDialog = new FileDialog(this, "Save Gene CSV File", FileDialog.SAVE);
        try {
            this.setIconImage(ImageIO.read(ClassLoader.getSystemResource("images/title-icon.png")));
        } catch (Exception e) {
            log.error("加载标题图片失败==>" + ExceptionUtils.getStackTrace(e));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ssrMinDiff = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ssrMaxDiff = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ssrRunBtn = new javax.swing.JButton();
        ssrSourceFile = new javax.swing.JTextField();
        ssrTargetFile = new javax.swing.JTextField();
        ssrCsvBtn = new javax.swing.JButton();
        tSsrSelFileBtn = new javax.swing.JButton();
        sSsrSelFileBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        kaspMinDiff = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kaspMaxDiff = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kaspRunBtn = new javax.swing.JButton();
        kaspSourceFile = new javax.swing.JTextField();
        kaspTargetFile = new javax.swing.JTextField();
        kaspCsvBtn = new javax.swing.JButton();
        tKaspSelFileBtn = new javax.swing.JButton();
        sKaspSelFileBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        chipMinDiff = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        chipMaxDiff = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        chipRunBtn = new javax.swing.JButton();
        chipSourceFile = new javax.swing.JTextField();
        chipTargetFile = new javax.swing.JTextField();
        chipCsvBtn = new javax.swing.JButton();
        tChipSelFileBtn = new javax.swing.JButton();
        sChipSelFileBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FCGS algorithm");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Minimum number of difference loci");

        ssrMinDiff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ssrMinDiffKeyPressed(evt);
            }
        });

        jLabel2.setText("Maximum number of difference loci");

        ssrMaxDiff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ssrMaxDiffKeyPressed(evt);
            }
        });

        jLabel3.setText("Source fingerprints CSV");

        jLabel4.setText("Comparison fingerprint CSV");

        jLabel5.setText("Fingerprint CSV template");

        ssrRunBtn.setText("Start Compare");
        ssrRunBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ssrRunBtnMouseClicked(evt);
            }
        });
        ssrRunBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssrRunBtnActionPerformed(evt);
            }
        });

        ssrSourceFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ssrSourceFileMouseClicked(evt);
            }
        });

        ssrTargetFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ssrTargetFileMouseClicked(evt);
            }
        });

        ssrCsvBtn.setText("Download Template");
        ssrCsvBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ssrCsvBtnMouseClicked(evt);
            }
        });
        ssrCsvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssrCsvBtnActionPerformed(evt);
            }
        });

        tSsrSelFileBtn.setText("Select File");
        tSsrSelFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tSsrSelFileBtnMouseClicked(evt);
            }
        });
        tSsrSelFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSsrSelFileBtnActionPerformed(evt);
            }
        });

        sSsrSelFileBtn.setText("Select File");
        sSsrSelFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sSsrSelFileBtnMouseClicked(evt);
            }
        });
        sSsrSelFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sSsrSelFileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ssrSourceFile)
                            .addComponent(ssrTargetFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tSsrSelFileBtn)
                            .addComponent(sSsrSelFileBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ssrCsvBtn)
                            .addComponent(ssrRunBtn))
                        .addGap(0, 213, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ssrMaxDiff)
                            .addComponent(ssrMinDiff))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ssrMinDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ssrMaxDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ssrSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sSsrSelFileBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ssrTargetFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tSsrSelFileBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ssrCsvBtn))
                .addGap(26, 26, 26)
                .addComponent(ssrRunBtn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Microsatellite", jPanel1);

        jLabel6.setText("Minimum number of difference loci");

        kaspMinDiff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kaspMinDiffKeyPressed(evt);
            }
        });

        jLabel7.setText("Maximum number of difference loci");

        kaspMaxDiff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kaspMaxDiffKeyPressed(evt);
            }
        });

        jLabel8.setText("Source fingerprints CSV");

        jLabel9.setText("Comparison fingerprint CSV");

        jLabel10.setText("Fingerprint CSV template");

        kaspRunBtn.setText("Start Compare");
        kaspRunBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kaspRunBtnMouseClicked(evt);
            }
        });

        kaspSourceFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kaspSourceFileMouseClicked(evt);
            }
        });

        kaspTargetFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kaspTargetFileMouseClicked(evt);
            }
        });

        kaspCsvBtn.setText("Download Template");
        kaspCsvBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kaspCsvBtnMouseClicked(evt);
            }
        });
        kaspCsvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaspCsvBtnActionPerformed(evt);
            }
        });

        tKaspSelFileBtn.setText("Select File");
        tKaspSelFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tKaspSelFileBtnMouseClicked(evt);
            }
        });
        tKaspSelFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKaspSelFileBtnActionPerformed(evt);
            }
        });

        sKaspSelFileBtn.setText("Select File");
        sKaspSelFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sKaspSelFileBtnMouseClicked(evt);
            }
        });
        sKaspSelFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sKaspSelFileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kaspSourceFile)
                            .addComponent(kaspTargetFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tKaspSelFileBtn)
                            .addComponent(sKaspSelFileBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kaspCsvBtn)
                            .addComponent(kaspRunBtn))
                        .addGap(0, 213, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kaspMaxDiff)
                            .addComponent(kaspMinDiff))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kaspMinDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kaspMaxDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(kaspSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sKaspSelFileBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tKaspSelFileBtn)
                            .addComponent(kaspTargetFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(kaspCsvBtn))
                .addGap(26, 26, 26)
                .addComponent(kaspRunBtn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SNP KASP", jPanel2);

        jLabel11.setText("Minimum number of difference loci");

        chipMinDiff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chipMinDiffKeyPressed(evt);
            }
        });

        jLabel12.setText("Maximum number of difference loci");

        chipMaxDiff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chipMaxDiffKeyPressed(evt);
            }
        });

        jLabel13.setText("Source fingerprints CSV");

        jLabel14.setText("Comparison fingerprint CSV");

        jLabel15.setText("Fingerprint CSV template");

        chipRunBtn.setText("Start Compare");
        chipRunBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chipRunBtnMouseClicked(evt);
            }
        });

        chipSourceFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chipSourceFileMouseClicked(evt);
            }
        });
        chipSourceFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chipSourceFileActionPerformed(evt);
            }
        });

        chipTargetFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chipTargetFileMouseClicked(evt);
            }
        });

        chipCsvBtn.setText("Download Template");
        chipCsvBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chipCsvBtnMouseClicked(evt);
            }
        });
        chipCsvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chipCsvBtnActionPerformed(evt);
            }
        });

        tChipSelFileBtn.setText("Select File");
        tChipSelFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tChipSelFileBtnMouseClicked(evt);
            }
        });
        tChipSelFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tChipSelFileBtnActionPerformed(evt);
            }
        });

        sChipSelFileBtn.setText("Select File");
        sChipSelFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sChipSelFileBtnMouseClicked(evt);
            }
        });
        sChipSelFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sChipSelFileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chipSourceFile)
                            .addComponent(chipTargetFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tChipSelFileBtn)
                            .addComponent(sChipSelFileBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chipCsvBtn)
                            .addComponent(chipRunBtn))
                        .addGap(0, 213, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chipMaxDiff)
                            .addComponent(chipMinDiff))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(chipMinDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(chipMaxDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(chipSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sChipSelFileBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(chipTargetFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tChipSelFileBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(chipCsvBtn))
                .addGap(26, 26, 26)
                .addComponent(chipRunBtn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SNP-arrays", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ssrCsvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssrCsvBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssrCsvBtnActionPerformed

    private void kaspCsvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaspCsvBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kaspCsvBtnActionPerformed

    private void chipCsvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chipCsvBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chipCsvBtnActionPerformed

    private void chipSourceFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chipSourceFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chipSourceFileActionPerformed

    private void ssrCsvBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssrCsvBtnMouseClicked
        log.info("开始下载SSR数据文件模板....");

        //保存的模板
        SsrTemplateEnum templateEnum = SsrTemplateEnum.FCGS_SSR_GENE_CSV;

        saveGeneTemplateFile(templateEnum);
    }//GEN-LAST:event_ssrCsvBtnMouseClicked

    private void kaspCsvBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kaspCsvBtnMouseClicked
        log.info("开始下载SNP-KASP数据文件模板....");

        //保存的模板
        SsrTemplateEnum templateEnum = SsrTemplateEnum.FCGS_KASP_GENE_CSV;

        saveGeneTemplateFile(templateEnum);
    }//GEN-LAST:event_kaspCsvBtnMouseClicked

    private void chipCsvBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chipCsvBtnMouseClicked
        log.info("开始下载SNP-arrays数据文件模板....");

        //保存的模板
        SsrTemplateEnum templateEnum = SsrTemplateEnum.FCGS_CHIP_GENE_CSV;

        saveGeneTemplateFile(templateEnum);
    }//GEN-LAST:event_chipCsvBtnMouseClicked

    private void ssrSourceFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssrSourceFileMouseClicked
        this.selGeneCsvFile(ssrSourceFile);
    }//GEN-LAST:event_ssrSourceFileMouseClicked

    private void ssrTargetFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssrTargetFileMouseClicked
        this.selGeneCsvFile(ssrTargetFile);
    }//GEN-LAST:event_ssrTargetFileMouseClicked

    private void kaspSourceFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kaspSourceFileMouseClicked
        this.selGeneCsvFile(kaspSourceFile);
    }//GEN-LAST:event_kaspSourceFileMouseClicked

    private void kaspTargetFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kaspTargetFileMouseClicked
        this.selGeneCsvFile(kaspTargetFile);
    }//GEN-LAST:event_kaspTargetFileMouseClicked

    private void chipSourceFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chipSourceFileMouseClicked
        this.selGeneCsvFile(chipSourceFile);
    }//GEN-LAST:event_chipSourceFileMouseClicked

    private void chipTargetFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chipTargetFileMouseClicked
        this.selGeneCsvFile(chipTargetFile);
    }//GEN-LAST:event_chipTargetFileMouseClicked

    private void ssrMinDiffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ssrMinDiffKeyPressed
        limitInputNumber(evt);
    }//GEN-LAST:event_ssrMinDiffKeyPressed

    private void ssrMaxDiffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ssrMaxDiffKeyPressed
        limitInputNumber(evt);
    }//GEN-LAST:event_ssrMaxDiffKeyPressed

    private void kaspMinDiffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kaspMinDiffKeyPressed
        limitInputNumber(evt);
    }//GEN-LAST:event_kaspMinDiffKeyPressed

    private void kaspMaxDiffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kaspMaxDiffKeyPressed
        limitInputNumber(evt);
    }//GEN-LAST:event_kaspMaxDiffKeyPressed

    private void chipMinDiffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chipMinDiffKeyPressed
        limitInputNumber(evt);
    }//GEN-LAST:event_chipMinDiffKeyPressed

    private void chipMaxDiffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chipMaxDiffKeyPressed
        limitInputNumber(evt);
    }//GEN-LAST:event_chipMaxDiffKeyPressed

    private void tSsrSelFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSsrSelFileBtnActionPerformed
    }//GEN-LAST:event_tSsrSelFileBtnActionPerformed

    private void sSsrSelFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sSsrSelFileBtnActionPerformed
    }//GEN-LAST:event_sSsrSelFileBtnActionPerformed

    private void tKaspSelFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKaspSelFileBtnActionPerformed
    }//GEN-LAST:event_tKaspSelFileBtnActionPerformed

    private void sKaspSelFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sKaspSelFileBtnActionPerformed
    }//GEN-LAST:event_sKaspSelFileBtnActionPerformed

    private void tChipSelFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tChipSelFileBtnActionPerformed
    }//GEN-LAST:event_tChipSelFileBtnActionPerformed

    private void sChipSelFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sChipSelFileBtnActionPerformed
    }//GEN-LAST:event_sChipSelFileBtnActionPerformed

    private void sSsrSelFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sSsrSelFileBtnMouseClicked
        this.selGeneCsvFile(ssrSourceFile);
    }//GEN-LAST:event_sSsrSelFileBtnMouseClicked

    private void tSsrSelFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tSsrSelFileBtnMouseClicked
        this.selGeneCsvFile(ssrTargetFile);
    }//GEN-LAST:event_tSsrSelFileBtnMouseClicked

    private void sKaspSelFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sKaspSelFileBtnMouseClicked
        this.selGeneCsvFile(kaspSourceFile);
    }//GEN-LAST:event_sKaspSelFileBtnMouseClicked

    private void tKaspSelFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tKaspSelFileBtnMouseClicked
        this.selGeneCsvFile(kaspTargetFile);
    }//GEN-LAST:event_tKaspSelFileBtnMouseClicked

    private void sChipSelFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sChipSelFileBtnMouseClicked
        this.selGeneCsvFile(chipSourceFile);
    }//GEN-LAST:event_sChipSelFileBtnMouseClicked

    private void tChipSelFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tChipSelFileBtnMouseClicked
        this.selGeneCsvFile(chipTargetFile);
    }//GEN-LAST:event_tChipSelFileBtnMouseClicked

    private void ssrRunBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssrRunBtnMouseClicked
        FcgsGuiRunner runner = new FcgsGuiRunner();
        GCResults results = runner.compare(this, TagTypeEnum.MICROSATELLITE);

        openResultModel(results);
    }//GEN-LAST:event_ssrRunBtnMouseClicked

    private void openResultModel(GCResults results) {
        FcgsResultFrame fcgsResultFrame = new FcgsResultFrame();
        fcgsResultFrame.setGcResults(results);
        fcgsResultFrame.setTitle("Gene Compare Result");
        fcgsResultFrame.setLocationRelativeTo(null);//窗口居中
        fcgsResultFrame.setLayout(null);
        fcgsResultFrame.setVisible(true);
    }

    private void kaspRunBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kaspRunBtnMouseClicked
        FcgsGuiRunner runner = new FcgsGuiRunner();
        GCResults results = runner.compare(this, TagTypeEnum.KASP);

        openResultModel(results);
    }//GEN-LAST:event_kaspRunBtnMouseClicked

    private void chipRunBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chipRunBtnMouseClicked
        FcgsGuiRunner runner = new FcgsGuiRunner();
        GCResults results = runner.compare(this, TagTypeEnum.CHIP);

        openResultModel(results);
    }//GEN-LAST:event_chipRunBtnMouseClicked

    private void ssrRunBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssrRunBtnActionPerformed
        // 禁用主窗口
        //this.setEnabled(false);
    }//GEN-LAST:event_ssrRunBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FcgsMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FcgsMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FcgsMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FcgsMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FcgsMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chipCsvBtn;
    private javax.swing.JTextField chipMaxDiff;
    private javax.swing.JTextField chipMinDiff;
    private javax.swing.JButton chipRunBtn;
    private javax.swing.JTextField chipSourceFile;
    private javax.swing.JTextField chipTargetFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton kaspCsvBtn;
    private javax.swing.JTextField kaspMaxDiff;
    private javax.swing.JTextField kaspMinDiff;
    private javax.swing.JButton kaspRunBtn;
    private javax.swing.JTextField kaspSourceFile;
    private javax.swing.JTextField kaspTargetFile;
    private javax.swing.JButton sChipSelFileBtn;
    private javax.swing.JButton sKaspSelFileBtn;
    private javax.swing.JButton sSsrSelFileBtn;
    private javax.swing.JButton ssrCsvBtn;
    private javax.swing.JTextField ssrMaxDiff;
    private javax.swing.JTextField ssrMinDiff;
    private javax.swing.JButton ssrRunBtn;
    private javax.swing.JTextField ssrSourceFile;
    private javax.swing.JTextField ssrTargetFile;
    private javax.swing.JButton tChipSelFileBtn;
    private javax.swing.JButton tKaspSelFileBtn;
    private javax.swing.JButton tSsrSelFileBtn;
    // End of variables declaration//GEN-END:variables

    private FileDialog openDialog;
    private FileDialog saveDialog;

    /**
     * 保存指纹数据模板文件到磁盘
     *
     * @param templateEnum
     */
    private void saveGeneTemplateFile(SsrTemplateEnum templateEnum) {
        this.saveDialog.setVisible(true);//显示打开文件对话框

        String dirpath = saveDialog.getDirectory();//获取打开文件路径并保存到字符串中。
        String fileName = saveDialog.getFile();//获取打开文件名称并保存到字符串中

        if (StringUtils.isBlank(dirpath)) {//判断路径和文件是否为空
            return;
        }

        String ext = FilenameUtils.getExtension(fileName);

        if (StringUtils.isBlank(fileName)) {//未填写文件名则使用模板中定义的文件名
            fileName = templateEnum.getDescName();
        } else if (!"csv".equalsIgnoreCase(ext)) {
            fileName += ".csv";
        }

        log.info("选择保存文件的路径为=>" + dirpath + fileName);
        try {
            TemplateReader templateReader = new SimpleTemplateReader();
            byte[] contents = templateReader.read(templateEnum);
            FileUtils.writeByteArrayToFile(new File(dirpath, fileName), contents);
        } catch (Exception e) {
            log.error("下载指纹数据模板文件失败!", ExceptionUtils.getStackTrace(e));
            JOptionPane.showMessageDialog(null, "Failed to download fingerprint data template file!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * 选择指纹数据文件并设置到文本框中
     *
     * @param textField
     */
    private void selGeneCsvFile(JTextField textField) {
        this.openDialog.setVisible(true);//显示打开文件对话框

        textField.setText("");

        String dirpath = openDialog.getDirectory();//获取打开文件路径并保存到字符串中。
        String fileName = openDialog.getFile();//获取打开文件名称并保存到字符串中

        if (StringUtils.isBlank(dirpath) || StringUtils.isBlank(fileName)) {//判断路径和文件是否为空
            return;
        }

        String ext = FilenameUtils.getExtension(fileName);
        if (!"csv".equalsIgnoreCase(ext)) {
            JOptionPane.showMessageDialog(null, "Incorrect fingerprint data file extension!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        textField.setText(dirpath + fileName);

        log.info("选择保存文件的路径为=>" + dirpath + fileName);
    }

    /**
     * 限制只能输入数字
     *
     * @param evt
     */
    private void limitInputNumber(KeyEvent evt) {
    }

    public JTextField getChipMaxDiff() {
        return chipMaxDiff;
    }

    public JTextField getChipMinDiff() {
        return chipMinDiff;
    }

    public JTextField getChipSourceFile() {
        return chipSourceFile;
    }

    public JTextField getChipTargetFile() {
        return chipTargetFile;
    }

    public JTextField getKaspMaxDiff() {
        return kaspMaxDiff;
    }

    public JTextField getKaspMinDiff() {
        return kaspMinDiff;
    }

    public JTextField getKaspSourceFile() {
        return kaspSourceFile;
    }

    public JTextField getKaspTargetFile() {
        return kaspTargetFile;
    }

    public JTextField getSsrMaxDiff() {
        return ssrMaxDiff;
    }

    public JTextField getSsrMinDiff() {
        return ssrMinDiff;
    }

    public JTextField getSsrSourceFile() {
        return ssrSourceFile;
    }

    public JTextField getSsrTargetFile() {
        return ssrTargetFile;
    }
}
